version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: saud-postgresql_web_1
      APP_PORT: 8081
  db:
    image: postgres:16.15@sha256:1a6ab3f5345eb6dbe04a1349529caabdb0ab09293a09590fad07b2246bfa4b54
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
    - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${APP_PASSWORD}
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 10
  web:
    image: sosedoff/pgweb:0.17.0@sha256:a5256d416e2e8b92d69a4459058e3eca33a9f075d8325491644411d0bc3bd70b
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:${APP_PASSWORD}@saud-postgresql_db_1:5432/postgres?sslmode=disable
