version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: saud-netdata_web_1
      APP_PORT: 19999
  web:
    image: netdata/netdata:v2.11.1@sha256:21970e176031fdb9469503534d01b4dc2fe2c36d369a5a4be74b6ec5c8b7a5c3
    restart: on-failure
    hostname: umbrel-netdata
    pid: host
    cap_add:
    - SYS_PTRACE
    - SYS_ADMIN
    security_opt:
    - apparmor:unconfined
    environment:
      DO_NOT_TRACK: '1'
      NETDATA_DISABLE_CLOUD: '1'
    volumes:
    - ${APP_DATA_DIR}/data/config:/etc/netdata
    - ${APP_DATA_DIR}/data/lib:/var/lib/netdata
    - ${APP_DATA_DIR}/data/cache:/var/cache/netdata
    - /etc/passwd:/host/etc/passwd:ro
    - /etc/group:/host/etc/group:ro
    - /etc/localtime:/etc/localtime:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /etc/os-release:/host/etc/os-release:ro
